base:
  SYSTEM_WINDOW_SERVICE: 1
  ENABLE_BUFFER_QUEUE_BY_NAME: 1
  ENABLE_WINDOW_LIMIT_MAX: 20
  ENABLE_TRANSITION_ANIMATION: 1
  SYSTEM_WINDOW_USE_VSYNC_EVENT: 0
  SYSTEM_WINDOW_FBDEV_DEVICEPATH: "/dev/fb0"
  SYSTEM_WINDOW_TOUCHPAD_DEVICEPATH: "/dev/input0"
  APP_WINDOW_RENDER_MODE: 1
  WM_COMMAND: 0
